### ISSUE TITLE
serializerjs-es5.js:138:25 require non existing module in directory

### ISSUE THREAD

**Issue by chriscx** [haircvt/serializerjs#1]
SerializerAware module is not being compiled in the dist directory

Error: Cannot find module './SerializerAware'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../node_modules/serializerjs/dist/serializerjs-es5.js:138:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by theofidry** [comment]
Fixed with the last tagged version (v1.0.0-beta). I will update the documentation shortly on how to use it :)
